context:
  version: "2.1.1"
  python_min: "3.12"

package:
  name: graphatoms
  version: ${{ version }}

source:
  url: https://github.com/LiuGaoyong/GraphAtoms/releases/download/v${{ version }}/graphatoms-${{ version }}.tar.gz
  sha256: 83c0edb14c50b84561f921c981efc93188bb6ea2fed6c31bd7077122f286b8d6
  patches:
    - v211.patch

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - tomli
    - ase
    - array-api-compat >=1.15
    - array-api-extra >=0.11
    - array-api-strict >=2.5
    - h5py
    - loguru
    - pymatgen >2023.6
    - rdkit >=2025
    - scikit-learn >=1.5
    - pyarrow
    - python-igraph >=0.11
    - hydra-core
    - numpy >=2.0
    - numpydantic
    - ovld >=0.5
    - pydantic >=2.11
    - python-snappy >=0.7.3
    - ray-default >=2.49
    - tomli-w
    - typing-extensions
    - executorlib
    - typer

tests:
  - python:
      imports:
        - graphatoms
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/LiuGaoyong/graphatoms
  summary: The Chemical Core Class for Graph Theory Analysis.
  description: |
    The Chemical Core Class for Graph Theory Analysis & Graph Neural Network.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/LiuGaoyong/graphatoms

extra:
  recipe-maintainers:
    - LiuGaoyong
