context:
  version: "1.1.4"
  python_min: "3.12"

package:
  name: graphatoms
  version: ${{ version }}

source:
  url: https://github.com/LiuGaoyong/GraphAtoms/releases/download/v${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8d641e40e0724eea4b5c2e3c74423d29a9bf1f478443094e10ce43d7dbc49158

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - tomli
    - ase
    - array-api-compat >=1.15
    - array-api-extra >=0.11
    - array-api-strict >=2.5
    - h5py
    - loguru
    - pymatgen >2023.6
    - rdkit >=2025
    - scikit-learn >=1.5
    - pyarrow
    - python-igraph >=0.11
    - hydra-core
    - numpy >=2.0
    - numpydantic
    - ovld >=0.5
    - pydantic >=2.11
    - python-snappy >=0.7.3
    - tomli-w
    - typing-extensions

tests:
  - python:
      imports:
        - graphatoms
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/LiuGaoyong/graphatoms
  summary: The Chemical Core Class for Graph Theory Analysis.
  description: |
    The Chemical Core Class for Graph Theory Analysis & Graph Neural Network.
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/LiuGaoyong/graphatoms

extra:
  recipe-maintainers:
    - LiuGaoyong
